DROP DATABASE IF EXISTS `Fresh_tomatoes`;

CREATE DATABASE `Fresh_tomatoes`;

USE `Fresh_tomatoes`;

DROP TABLE IF EXISTS `gebruikers`;

CREATE TABLE gebruikers (
    id MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(30) NOT NULL,
    password varchar(30) NULL,
    name VARCHAR(30) NOT NULL
);

USE `Fresh_tomatoes`;
DROP TABLE IF EXISTS `favoriet`;
CREATE TABLE `favoriet` (
    id MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(100) NOT NULL,
    film_id VARCHAR(100),
    serie_id varchar(100)
);

USE `Fresh_tomatoes`;
DROP TABLE IF EXISTS `adminlogin`;
CREATE TABLE IF NOT EXISTS `adminlogin` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(100) NOT NULL,
  `password` varchar(100) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

INSERT INTO `adminlogin` (`id`, `username`, `password`) VALUES (NULL, 'admin@admin.com', 'admin'), (NULL, 'admin2@admin.com', 'admin2');

USE `Fresh_tomatoes`;
DROP TABLE IF EXISTS `film`;
CREATE TABLE `film` (
    id MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    titel VARCHAR(100) NOT NULL,
    score VARCHAR(100) NOT NULL,
    genre varchar(100) NOT NULL,
    taal varchar(100) NOT NULL,
    duur VARCHAR(100) NOT NULL,
    datum VARCHAR(100) NULL,
    beschrijving TEXT NOT NULL,
    youtube_trailer_id VARCHAR(100) NOT NULL,
    foto varchar(100) NOT NULL,
    type ENUM('netflix', 'normaal')
);
INSERT INTO film (titel, score, genre, taal, duur, datum, beschrijving, youtube_trailer_id, foto, type) VALUES
    ('Maid in Manhattan', 5.3, 'romantiek', 'Engels' , '105 minuten', '13-12-2002', 'Een vrouw begint een baan als kamermeisje in een luxe hotel. Ze wordt verliefd op een beoogde opvolger van een politieke familie. Hij denkt met een vrouw uit hoge kringen te maken te hebben, waardoor ze al snel inzicht krijgt in het leven van een man die ze normaal gesproken alleen van een afstand beoordeeld zou hebben.', 'https://www.youtube.com/embed/v1dv-skGIYY', 'maid_in_manhattan.jpg', 'normaal'),
    ('Think Like a Man', 6.5, 'romantiek', 'Engels' , '123 minuten','20-4-2012' , 'De levens van vier jonge mannen komen volledig op zijn kop te staan nadat hun geliefde vrouwen het boek hebben gekocht van Harvey, een relatie expert, wiens advies zij maar al te graag opvolgen. Probleem is alleen dat Harvey zelf moeite heeft om zijn relatie op orde te krijgen. Als de mannen gezamenlijk lucht van het zaakje krijgen besluiten ze de rollen om te draaien en de vrouwen flink terug te pakken.', 'https://www.youtube.com/embed/vxTN4eX4Vss', 'think_like_a_man.jpg', 'normaal'),
    ('The notebook', 7.8, 'romantiek', 'Engels' , '123 minuten', '7-11-2004', 'Allie Hamilton komt begin jaren 40 naar het plaatsje Seabrook in North Carolina om vakantie te vieren met haar familie. Daar ontmoet ze de knappe Noah Calhoun die vanaf t eerste moment verliefd op haar is. Ondanks hun zeer verschillende achtergronden beleven de twee een zomer vol hartstocht en passie. Maar als Allie verhuist en Noah zich aanmeldt bij het leger lijkt de liefde voorgoed voorbij.', 'https://www.youtube.com/embed/BjJcYdEOI0k', 'notebook.jpg', 'normaal'),
    ('Dirty Dancing', 7.0, 'romantiek', 'Engels' , '100 minuten', '3-12-1987', 'Zomer 1963. De 17-jarige naïeve Frances Baby Houseman brengt met haar ouders en haar oudere zus Marjorie de vakantie door op het resort van het hotel Catshill. Baby ontmoet daar de verveelde dansleraar van het hotel Johnny Castle. Johnny brengt Baby dirty dancing bij, ze wordt zijn pupil en ze zet haar eerste schreden in de liefde.', 'https://www.youtube.com/embed/eIcmQNy9FsM', 'Dirty_Dancing.jpg', 'normaal'),
    ('The vow', 6.8, 'romantiek', 'Engels' , '104 minuten', '3-5-2012', 'Een vrouw raakt na een auto-ongeval in een coma. Als ze terug bij bewustzijn komt, is ze haar geheugen en alle herinneringen van de voorbije vijf jaar kwijt. Ze heeft er ook geen flauw benul van wie haar man is. Hij zal opnieuw haar hart voor zich moeten winnen.', 'https://www.youtube.com/embed/tdF01cA7jOE', 'the_vow.jpg', 'normaal'),
    ('He is all that', 4.4, 'romantiek', 'Engels' , '88 minuten', '25-8-2021', 'Nieuwe interpretatie van de originele tienerfilm Shes All That uit 1999. Influencer Padgett Sawyer (Addison Rae) neemt de uitdaging aan om de antisociale Cameron Kweller (Tanner Buchanan) tot koning van het eindejaarsbal te kronen. Het wordt allemaal wat gecompliceerder wanneer ze gevoelens voor hem begint te ontwikkelen...', 'https://www.youtube.com/embed/6HaVRjpU_ro', 'hes_al_that.jpg', 'netflix'),
    ('The kissing booth', 5.9, 'romantiek', 'Engels' , '105 minuten', '11-3-2018', 'Elle Evans, een zestienjarig meisje, is populair en feest graag maar is nog nooit gekust. De zaken nemen een wending die Elle nooit had verwacht wanneer ze tijdens carnaval terechtkomt bij een attractie genaamd kissing booth. Daar staat ze plots oog in oog met de jongen waar ze al lang verliefd op is - de broer van haar beste vriend, Noah. Elle wordt vervolgens meegesleept in een romance met de coolste jongen op school.', 'https://www.youtube.com/embed/4CkmmcgMOqQ', 'the_kissing_booth.jpg', 'netflix'),
    ('Tall Girl', 5.2, 'romantiek', 'Engels' , '101 minuten', '13-9-2019', 'De 16-jarige Jodi, die 1,90 m lang is, en heeft moeite met haar lengte. Ze moet leren te omarmen wat haar anders maakt. Ze heeft nog nooit een vriendje gehad. Dat zou kunnen veranderen wanneer er een lange uitwisselingsstudent op haar school komt...', 'https://www.youtube.com/embed/NfpXeLVzJIw', 'tall_girl.jpg', 'netflix'),
    ('Let it snow ', 5.8, 'romantiek', 'Engels' , '93 minuten', '8-11-2019', 'Wanneer een klein dorpje op kerstavond ondergesneeuwd wordt, veranderen de vriendschappen en liefdeslevens van een groep middelbare scholieren. Een gestrande popster, een groep competitieve dansers, een mysterieuze vrouw gewikkeld in aluminiumfolie en een episch feest in de lokale Waffle Town. De volgende ochtend zal niets meer hetzelfde zijn...', 'https://www.youtube.com/embed/pitxxQYZcug', 'let_it_snow.jpg', 'netflix'),
    ('Love hard', 6.3, 'romantiek', 'Engels' , '104 minuten', '5-11-2021', 'De hopeloze, maar eeuwig single blijvende journaliste Natalie uit Los Angeles denkt dat de dingen beginnen te verbeteren als ze Tag, een dromerige jongen van de oostkust, aan de haak slaat via een dating-app. Ze besluit hem voor de feestdagen te verrassen. Maar dan ontdekt ze dat ze wordt opgelicht door de jeugdvriend van Tag, Josh, die al evenveel pech heeft in de liefde. Toch doet ze een poging om weer verliefd te worden.', 'https://www.youtube.com/embed/3boMRfx6cjE', 'love_hard.jpg', 'netflix'),
    ('Oceans eleven', 7.7, 'triller', 'Engels', '116 minuten', '7-12-2001', 'De crimineel Danny Ocean komt na een gevangenisstraf van vier jaar eindelijk vrij. Hij besluit zijn herwonnen vrijheid meteen goed te gebruiken door drie casinos in Las Vegas te beroven. Om deze bijna onmogelijke klus te klaren, verzamelt hij een grote crew professionals om zich heen. Al snel blijkt dat er voor Danny meer op het spel staat dan alleen maar geld: zijn ex-vrouw Tess is namelijk de nieuwe vriendin van Terry Benedict, de eigenaar van de casinos die hij wil beroven.', 'https://www.youtube.com/embed/imm6OR605UI', 'ocean_eleven.jpg', 'normaal'),
    ('Fight club', 8.8, 'triller', 'Engels', '139 minuten', '4-11-1999', 'Een man die voor een verzekeringsmaatschappij stad en land afreist als schade-expert, lijdt aan chronische slapeloosheid. Hij krijgt van een arts echter geen medicatie, maar een snerende opmerking: Ga maar eens kijken bij een praatgroep voor terminaal zieken, dan zal je zien wat pijn écht inhoudt. De man neemt het serieus en bezoekt een praatgroep, waar men aanneemt dat hij ook terminaal ziek is. Hij vindt er een uitlaatklep en bezoekt vervolgens ook andere praatgroepen. Bij één van die bezoeken treft hij de mysterieuze Marla Singer. Als hij op een dag thuis komt van een vlucht, blijkt er een explosie in zijn appartement te zijn geweest. Hij belt Tyler Durden, een extravagante man die hij net daarvoor in het vliegtuig ontmoet heeft. Tyler neemt op, en ze gaan samen een biertje drinken. Tyler blijkt er nogal eigenzinnige ideeën op na te houden.', 'https://www.youtube.com/embed/qtRKdVHc-cE', 'fight_club.jpg', 'normaal'),
    ('Rebecca', 6.0, 'triller', 'Engels', '121 minuten', '16-10-2020', 'Een jonge vrouw van eenvoudige komaf trouwt met een gedistingeerde kasteelheer, Maxim de Winter genaamd. Hun huwelijksgeluk lijkt van korte duur door de herinnering aan Rebecca, de vorige vrouw van Maxim. De oude geliefde van Maxim kwam onder duistere omstandigheden om het leven, maar haar geest lijkt nog altijd rond te waren.', 'https://www.youtube.com/embed/LFVhB54UqvQ', 'rebecca.jpg', 'normaal'),
    ('End of the road', 4.7, 'triller', 'Engels', '89 minuten', '9-9-202', 'Een reis per auto door het land verandert in een nachtmerrie voor de onlangs weduwe geworden Brenda, haar twee kinderen en haar broer Reggie. Na getuige te zijn geweest van een brute moord, bevindt de familie zich in het vizier van een mysterieuze moordenaar. Ze zijn alleen in de woestijn van New Mexico en afgesneden van elke hulp. Brenda wordt weldra in een dodelijk gevecht getrokken om haar familie in leven te houden.', 'https://www.youtube.com/embed/202KkD12AuI', 'end_of_the_road.jpg', 'normaal'),
    ('A simple favor', 6.8, 'triller', 'Engels', '117 minuten', '27-9-2018', 'Stephanie is moeder en vlogger. Haar beste vriendin, Emily, vraagt haar om haar zoontje Nicky mee te nemen uit school. Stephanie vangt wel vaker de beide jongetjes op als de succesvolle Emily voor haar werk van huis is. Maar deze keer komt Emily haar zoontje niet ophalen en ze reageert ook niet op telefoontjes. Stephanie probeert de waarheid te achterhalen van de plotselinge verdwijning van haar vriendin Emily uit hun kleine stadje. Ze wordt hierbij bijgestaan door Emilys echtgenoot Sean.', 'https://www.youtube.com/embed/rAqMlh0b2HU', 'a_simple_favor.jpg', 'normaal'),
    ('The weekend away', 5.6, 'triller', 'Engels' , '89 minuten', '3-3-2022', 'Kate en Orla zijn twee beste vriendinnen die persoonlijke tegenslagen hebben overwonnen. Wat het leven hen ook brengt, ieder keer kijken ze weer uit naar jaarlijkse weekendje weg. Dit jaar zijn ze op reis naar Kroatië. Alles is perfect totdat Orla wakker wordt en Kate vermist wordt. Met slechts een vage herinnering aan de vorige nacht en de politie die niet helpt, onthult haar verwoede zoektocht verwoestende geheimen dichter bij huis.', 'https://www.youtube.com/embed/XpfjN-7Hf-8', 'The_Weekend_Away_film_poster.png', 'netflix'),
    ('Mother/Android', 4.9, 'triller', 'Engels' , '110 minuten', '17-12-2021', 'Wanneer hun vaderland verstrikt raakt in een oorlog met betrekking tot artificiële intelligentie, poogt Georgia met haar vriendje Sam het conflict te ontvluchten. Het stel hoopt een veilig onderkomen te vinden, zeker nu in de laatste dagen voordat ze op bevallen staat. De twee komen terecht bij de vesting van de rebellerende androïden.', 'https://www.youtube.com/embed/JRl214mDZ-g', 'mother_android.jpg', 'netflix'),
    ('Bird box', 6.6, 'triller', 'Engels' , '123 minuten', '14-12-2018', 'In de nasleep van een wereldwijde dreiging van onbekende oorsprong moet Malorie de kracht vinden om haar kinderen veilig te kunnen stellen. Ze vlucht met ze weg via een verraderlijke rivier, op zoek naar een veilig onderkomen. Vanwege dodelijke onzichtbare krachten moeten ze hun weg blind vervolgen.', 'https://www.youtube.com/embed/o2AsIXSh2xo', 'Bird_Box.png', 'netflix'),
    ('Army of thieves', 6.4, 'triller', 'Engels', '127 minuten', '29-10-2021', 'We volgen Ludwig Dieter in de gebeurtenissen vóór Army of the Dead. Terwijl de zombie-uitbraak nog in een vroeg stadium zit, houdt Dieter zich bezig met kluizen kraken. Door een mysterieuze vrouw wordt hij benaderd om een overval te plegen. Hij stemt toe en voegt zich bij de meest gezochte criminelen op de lijst van Interpol, buitenbeentjes die graag in zijn voetsporen willen treden.', 'https://www.youtube.com/embed/Ith2WetKXlg', 'army_of_thieves.jpg', 'netflix'),
    ('Spiderhead', 5.4, 'triller', 'Engels' , '106 minuten', '11-6-2022', 'Escape from Spiderhead speelt zich af in de nabije toekomst, waarin twee veroordeelden in een voorziening wonen dat gerund wordt door een dokter. Deze dokter voert experimenten uit op de gevangenen met drugs die de emoties aantasten. De veroordeelden stemmen in met de situatie, in ruil voor een vermindering van hun celstraf. Maar na de proeven gaan ze zelf op onderzoek uit.', 'https://www.youtube.com/embed/BfsNfFoA0J0', 'Spiderhead.jpg', 'netflix'),
    ('Pitch perfect', 7.1, 'comedy', 'Engels', '112 minuten', '3-1-203', 'Twee concurrerende a capella zanggroepen, de Barden Bellas (allemaal meisjes) en de Barden Treblemakers (allemaal jongens), strijden om het “International Championship of Collegiate A Capella” (ICCA) te winnen, dat elk jaar in de lente gehouden wordt op Carnegie Hall. De Barden Bellas krijgen echter te maken met persoonlijke conflicten: hun zangeres Chloe heeft stemproblemen, velen van hen zijn afgestudeerd, en hun leider Aubrey probeert wanhopig te groep bijeen te houden. Dan wordt de eerstejaars studente Beca Mitchell in de groep opgenomen. De rebelse Beca heeft goede ideeën, maar deze worden routinematig neergesabeld door Aubrey. Ondertussen probeert Beca niet verliefd te worden op Jesse, een nieuw lid van de Treblemakers.', 'https://www.youtube.com/embed/X_bbBSYwlY8', 'pitch_perfect.jpg', 'normaal'),
    ('28 Days', 6.1, 'comedy', 'Engels', '103 minuten', '22-6-2000', 'Gwen Cummings is een succesvolle New Yorkse schrijfster, die er een wild uitgaanspatroon op na houdt. Ze duikt op in alle trendy clubs en is in beschonken toestand te vinden op elk feestje. Haar leven neemt een radicale wending wanneer ze op het huwelijksfeest van haar zus Lily volledig door het lint gaat. Ze wordt veroordeeld tot een afkickkuur van 28 dagen in een ontwenningskliniek. Gwen moet zich houden aan een strikt schema vol regels en afspraken. Ze komt al snel in conflict met zichzelf en alle andere patiënten. Maar de cynische Gwen wil zich niet neerleggen bij de normale gang van zaken in het instituut.', 'https://www.youtube.com/embed/y7RXmrlGe-k', '28_days.jpg', 'normaal'),
    ('Sex and the city', 5.7, 'comedy', 'Engels', '148 minuten', '12-6-2008', 'Sex and the City volgt de levens van vier vriendinnen in Manhattan, New York. Columniste Carrie (Sarah Jessica Parker), advocate Miranda (Cynthia Nixon), zakenvrouw Samantha (Kim Cattrall) en de brave Charlotte (Kristin Davis) zouden genoeg aan zichzelf moeten hebben, maar in plaats daarvan verdiepen de dames zich voortdurend in de levens van elkaar en proberen samen de juiste weg te vinde', 'https://www.youtube.com/embed/g9Mx2OLnoGI', 'sex_and_the_city.jpg', 'normaal'),
    ('Mamma Mia!', 6.5, 'comedy', 'Engels', '108 minuten', '17-9-208', 'Donna, een onafhankelijke, single moeder heeft een hotelletje op een idyllisch Grieks eiland. Ze staat op het punt om Sophie, de pittige dochter die ze alleen heeft grootgebracht, los te laten. Voor Sophies huwelijk heeft Donna haar twee oude hartsvrienden uitgenodigd: de praktische en no-nonsense Rosie en de rijke, meermalen gescheiden Tanya van haar vroegere backing-band Donna and the Dynamos. Maar Sophie heeft in het geheim zelf drie gasten uitgenodigd. Ze is op zoek gegaan naar de identiteit van haar vader die haar naar het altaar moet begeleiden en ze haalt drie mannen uit Donnas verleden naar het mediterrane paradijs waar ze 20 jaar daarvoor waren geweest. In de 24 chaotische, magische uren bloeit er nieuwe liefde op en oude romances vatten opnieuw vlam op dit weelderige eiland vol mogelijkheden.', 'https://www.youtube.com/embed/lkN-A00WLYE', 'mamma_mia.jpg', 'normaal'),
    ('Paddington', 7.3, 'comedy', 'Engels', '95 minuten', '11-2-2015', 'Een jonge Peruaanse beer, die een passie heeft voor alles wat Brits is, vertrekt naar Londen waar hij op zoek gaat naar een woning. Wanneer hij eenzaam en verloren op Paddington Station belandt, begint hij te beseffen dat het leven in de stad niet is wat hij zich ervan had voorgesteld. Maar dan ontmoet hij de vriendelijke familie Brown, die het label om zijn nek leest ("Pas alsjeblieft op deze beer, dankjewel") en hem een tijdelijk onderkomen aanbiedt.', 'https://www.youtube.com/embed/CxeBdrGGU8U', 'paddington.jpg', 'normaal'),
    ('Yesterday', 6.8, 'comedy', 'Engels', '116 minuten', '27-6-2019', 'Yesterday volgt het leven van een worstelende muzikant. Hij komt erachter dat hij van de ene op de andere dag de enige persoon op aarde is die zich de Beatles kan herinneren. Met de kennis van al hun muziek is hij vervolgens relevanter dan ooit.', 'https://www.youtube.com/embed/Ry9honCV3qc', 'yesterday_.jpg', 'netflix'),
    ('Little', 5.5, 'comedy', 'Engels', '109 minuten', '11-4-2019', 'Little volgt een vrouw die de kans krijgt om haar jeugd te herbeleven. Ze gaat terug in de tijd naar haar jongere zelf waar ze nog een zorgeloos leven leidde. Een leven waar langzamerhand de druk van volwassenheid om de hoek komt kijken en het haar destijds te veel werd.', 'https://www.youtube.com/embed/Qz65no3WnJk', 'little.jpg', 'netflix'),
    ('Set it up', 6.5, 'comedy', 'Engels', '105 minuten', '15-6-2018', 'Harper en Charlie zijn twee assistenten werkzaam in New York. Hun werkgevers zijn beiden verslaafd aan hun werk en maken het hun personeel weleens lastig. Harper en Charlie vinden hierop een oplossing en organiseren een date voor de bazen. Tijdens het plannen en uitvoeren van hun idee beseffen de assistenten dat er ook romantiek voor hen in de lucht hangt.', 'https://www.youtube.com/embed/X-eRc9PF3TU', 'set_it_up.jpg', 'netflix'),
    ('The f**k it list', 5.1, 'comedy', 'Engels', '103 minuten', '1-7-2020', 'Brett Blackmore is een high school leerling en een echte studiebol. Zijn leven valt in duigen door een misgelopen grap die hij heeft uitgehaald. Nu deelt hij een lijst van dingen die hij liever anders had gedaan en wellicht nog kan veranderen. Deze lijst gaat viraal en komt terecht bij veel jongeren, wat voor ophef zorgt.', 'https://www.youtube.com/embed/eyW5yoMpBtM', 'the_fack_it_list.jpg', 'netflix'),
    ('Dude', 5.1, 'comedy', 'Engels', '97 minuten', '20-4-2018', 'Vier beste vriendinnen zitten voor de laatste twee weken op de middelbare school. Ze krijgen te maken met verlies en grote levensveranderingen. Ze ervaren dit met een vreemde combinatie van verdriet en nostalgie terwijl ze hun verlies trachten te begrijpen.', 'https://www.youtube.com/embed/eIBQaDlR0tA', 'dude.jpg', 'netflix'),
    ('Get out', 7.7, 'horror', 'Engels', '104 minuten', '24-2-2017', 'Rose nodigt Chris uit om een weekend door te brengen met haar ouders. In eerste instantie denkt Chris dat het vreemde gedrag van de familie te maken heeft met hun interraciale relatie, maar gedurende het weekend ontdekt Chris de waarheid.', 'https://www.youtube.com/embed/DzfpyUB60YY','getout.jpg', 'normaal'),
    ('SAW VI', 8.2,'horror', 'Engels', '90 minuten' ,'3-1-2008', 'Wanneer er een videoband opduikt van Jigsaw gaan er alarmbellen af, want hij en Amanda zijn dood. Het spel is echter nog lang niet aan zijn eind. Twee FBI agenten proberen te puzzel op te lossen.', 'https://www.youtube.com/embed/hQ7JF5JZkoo', 'saw.jpg','normaal'),
    ('Final destination', 5.5,'horror', 'Engels', '120 minuten', '16-3-2000', 'Alex moet mee in een Boeing 747, maar hij ziet voor zich dat het toestel zal ontploffen. In paniek wordt hij, en enkele anderen, uit het toestel gezet en enkele momenten later ziet hij het toestel opstijgen en veranderen in een vuurbal. ','https://www.youtube.com/embed/lP4Psj7d1ZI','final.jpg' ,'normaal'),
    ('Resident Evil: Extinction', 7.2, 'horror', 'Engels', '130 minuten', '3-9-2007', 'Overlevenden van Raccoon City reizen door de Nevada-woestijn, hopende dat ze Alaska kunnen bereiken. Alice sluit zich bij deze karavaan aan. Samen binden ze de strijd aan tegen de hordes zombies en de kwaadaardige Umbrella Corporation.', 'https://www.youtube.com/embed/eDMjVARsCOk','residentevil2.jpg' ,'normaal'),
    ('V/H/S', 6, 'horror', 'Engels', '112 minuten','3-2-2012', 'Een groep criminelen wordt ingehuurd om in een vervallen huis een VHS tape op te halen. Ze worden echter geconfronteerd met gruwelijke videos terwijl ze op zoek zijn naar de juiste tape', 'https://www.youtube.com/embed/opnSln8Ue2U','vhs.jpg', 'normaal'),
    ('Top Gun: Maverick', 9.5, 'actie', 'Engels', '125 minuten', '2-6-2022', 'Na meer dan dertig jaar zit Maverick nog steeds op zijn plek bij de marine. Ineens moet hij de beste piloten voorbereiden om de moeilijkste missie ooit. Gaat het ze lukken? En onthoud; het gaat niet om het vliegtuig, maar om de piloot.', 'https://www.youtube.com/embed/giXco2jaZ_4','topgun.jpg', 'normaal'),
    ('The Batman', 8.7, 'actie', 'Engels', '154 minuten', '4-3-2022', 'Wanneer de Riddler, een seriemoordenaar, belangrijke politieke figuren in Gotham begint te vermoorden, wordt Batman gedwongen de verborgen corruptie van de stad te onderzoeken en de betrokkenheid van zijn familie in twijfel te trekken.', 'https://www.youtube.com/embed/mqqft2x_Aa4','batman.jpg', 'normaal'),
    ('Nobody', 8.9, 'actie', 'Engels', '138 minuten', '26-3-2021', 'Als er op een nacht twee dieven bij hem inbreken, weigert Hutch zichzelf en zijn gezin te verdedigen, in de hoop ernstig geweld te voorkomen. Na het incident ontwaakt er een woede in hem die hij lange tijd heeft onderdrukt.', 'https://www.youtube.com/embed/_2un1aU7mT0','nobody.jpg', 'normaal'),
    ('Fast & Furious 9', 8.6, 'actie', 'Engels', '136 minuten', '8-13-2021', 'Dominic Toretto leidt een rustig bestaan samen met Letty en hun zoontje Brian. Beiden weten ze dat het gevaar altijd op de loer ligt. Dit keer komt de dreiging uit Dom’s verleden. ', 'https://www.youtube.com/embed/d1j5NVYVIok','fast.jpg', 'normaal'),
    ('Rampage: Big Meets Bigger', 9, 'actie', 'Engels', '120 minuten', '12-4-2022', 'De film volgt Davis Okoye, een primatoloog die een bijzondere band heeft met een gorilla genaamd George. Wanneer een experiment mislukt, verandert George in een reusachtige monster. Okoye moet nu samenwerken met een bioloog om George te stoppen.', 'https://www.youtube.com/embed/rDgtKfshJ50','rampage.jpg', 'normaal'),
    ('Interstellar', 9, 'sci-fi', 'Engels', '173 minuten', '2-4-2014', 'Onze tijd op aarde lijkt voorbij, dus begint een groep ontdekkingsreizigers aan de belangrijkste missie uit de geschiedenis van de mens. Ze gaan op zoek naar een plek in de ruimte waar de mensheid kan voortbestaan.', 'https://www.youtube.com/embed/zSWdZVtXT7E','interstellar.jpg', 'normaal'),
    ('The Matrix Resurrections', 7.8, 'sci-fi', 'Engels', '142 minuten', '9-2-2022', 'Neo zit gevangen in de wereld van de Matrix, maar heeft dit niet door. Hij besluit een blauwe pil te nemen en naar de therapeut te gaan. Alles wordt anders als een man Neo verteld dat zijn realiteit nep is. Wat is zijn leven dan wel?', 'https://www.youtube.com/embed/9ix7TUGVYIo','matrix.jpg', 'normaal'),
    ('War for the Planet of the Apes', 8.6, 'sci-fi', 'Engels', '140 minuten', '8-4-2017', 'Caesar en zijn apen worden in een dodelijk conflict gedwongen. Wanneer Caesar en de kolonel oog in oog met elkaar staan, nemen ze het tegen elkaar op in een episch gevecht dat het lot van beide soorten zal bepalen. ', 'https://www.youtube.com/embed/qxjPjPzQ1iU','apes.jpg', 'normaal'),
    ('Pokémon Detective Pikachu', 8.6, 'sci-fi', 'Engels', '104 minuten', '5-8-2019', 'Wanneer top privé detective Harry Goodman mysterieus vermist raakt, gaat zijn zoon Tim naar hem opzoek. Hij krijgt hulp van Detective Pikachu . Het duo is vastberaden mysterie rondom Harry op te lossen. ', 'https://www.youtube.com/embed/1roy4o4tqQM','pikachu.jpg', 'normaal'),
    ('Ready Player One', 8.6, 'sci-fi', 'Engels', '140 minuten', '8-5-2018', 'De wereld staat op het punt van instorten. De mensen zoeken hun redding in OASIS, een VR universum, gemaakt door Halliday. Wanneer hij overlijdt, laat hij een fortuin na aan degene die het digitale Easter Egg vindt binnen OASIS. ', 'https://www.youtube.com/embed/cSp1dM2Vj48','playerone.jpg', 'normaal'),
    ('Inception', 8.8, 'sci-fi', 'Engels', '148 minuten', '3-10-2010', 'Dom Cobb (Leonardo DiCaprio) is een handige dief, gespecialiseerd in het stelen van waardevolle geheimen in de droomstaat van een mens, wanneer de geest het kwetsbaarst is. Dankzij die zeldzame gave is Cobb een veelgevraagde speler in de wereld van bedrijfsspionage, maar is hij ook in vele landen voortvluchtig. Daarnaast is hij alles kwijt wat hem ooit dierbaar was. Cobb krijgt echter de kans zijn oude leven weer terug te krijgen, in ruil voor het uitvoeren van een vrijwel onmogelijke taak: Cobb en zijn team van specialisten moeten deze keer geen idee stelen, maar het in iemands brein plaatsen. Als ze hierin slagen, zou het de perfecte misdaad zijn.', 'https://www.youtube.com/embed/YoHD9XEInc0','inception.jpg', 'netflix'),
    ('The Matrix', 8.7, 'sci-fi', 'Engels', '136 minuten', '31-3-1999', 'Neo (Keanu Reeves) is een programmeur die in zijn vrije tijd graag computerspelletjes speelt. Hij heeft een vriendin, Trinity (Carrie-Anne Moss), en een baan bij een softwarebedrijf. Neo is echter niet wie hij denkt te zijn. Hij is eigenlijk Thomas Anderson, een hacker die in het dagelijks leven als programmeur werkt.', 'https://www.youtube.com/embed/vKQi3bBA1y8','matrix1.jpg', 'netflix'),
    ('Back to the future', 8.5, 'sci-fi', 'Engels', '111 minuten', '2-7-1985', 'Marty McFly (Michael J. Fox) is een doorsnee tiener die bevriend is met de gekke uitvinder Doc Brown (Christopher Lloyd). Doc ontwerpt een tijdmachine waardoor Marty per ongeluk wordt teruggezonden naar 1955. Hier ontmoet hij zijn ouders die in deze tijd natuurlijk nog veel jonger zijn. Hij verstoort de ontmoeting met zijn ouders en moet hier alles aan doen om hen weer te herenigen.', 'https://www.youtube.com/embed/qvsgGtivCgs','future.jpg', 'netflix'),
    ('The Matrix Reloaded', 7.2, 'sci-fi', 'Engels', '138 minuten', '15-5-2003', 'De Matrix is een computerprogramma dat de mensheid al duizenden jaren in een illusie houdt. De Matrix is een wereld die op het eerste gezicht lijkt op de echte wereld, maar in werkelijkheid een computerprogramma is. De Matrix wordt beheerd door een supercomputer die de mensheid als een energiebron gebruikt. De Matrix is een soort droomwereld waarin de mensheid wordt gehouden in slaap door een stroom van elektriciteit die via de hersenen wordt gevoerd. De Matrix is een computerprogramma dat de mensheid al duizenden jaren in een illusie houdt. De Matrix is een wereld die op het eerste gezicht lijkt op de echte wereld, maar in werkelijkheid een computerprogramma is. De Matrix wordt beheerd door een supercomputer die de mensheid als een energiebron gebruikt. De Matrix is een soort droomwereld waarin de mensheid wordt gehouden in slaap door een stroom van elektriciteit die via de hersenen wordt gevoerd.', 'https://www.youtube.com/embed/kYzz0FSgpSU','matrixre.jpg', 'netflix'),
    ('The Matrix Revolutions', 6.7, 'sci-fi', 'Engels', '129 minuten', '5-11-2003', 'De Matrix is een computerprogramma dat de mensheid al duizenden jaren in een illusie houdt. De Matrix is een wereld die op het eerste gezicht lijkt op de echte wereld, maar in werkelijkheid een computerprogramma is. De Matrix wordt beheerd door een supercomputer die de mensheid als een energiebron gebruikt. De Matrix is een soort droomwereld waarin de mensheid wordt gehouden in slaap door een stroom van elektriciteit die via de hersenen wordt gevoerd.', 'https://www.youtube.com/embed/hMbexEPAOQI','matrixrev.jpg', 'netflix'),
    ('Django Unchained', 8.4, 'actie', 'Engels', '165 minuten', '18-1-2013', 'Django (Jamie Foxx) is een slaaf die samen met zijn vrouw Broomhilda (Kerry Washington) wordt gekocht door de sadistische plantage-eigenaar Calvin Candie (Leonardo DiCaprio). Django wordt door Candie verkocht aan de schurk Dr. King Schultz (Christoph Waltz), een Duitse tandarts die zich voordoet als een slaafjager. Schultz wil Candie ontmaskeren als een slavenhandelaar en Django helpt hem daarbij. In ruil daarvoor belooft Schultz Django te helpen zijn vrouw terug te vinden.', 'https://www.youtube.com/embed/_iH0UBYDI4g', 'django_unchained.jpg', 'netflix'),
    ('Spider-Man: No Way Home', 8.3, 'actie', 'Engels', '148 minuten', '16-12-2021', 'Spider-Man is ontmaskerd en kan zijn normale leven niet langer gescheiden houden van zijn gevaarlijke leven als superheld. Als hij Doctor Strange om hulp vraagt, staat er meer op het spel dan ooit tevoren. Dit dwingt hem onder ogen te zien wat het nu echt betekent om Spider-Man te zijn.', 'https://www.youtube.com/embed/JfVOs4VSpmA', 'spiderman_no_way_home.jpg', 'netflix'),
    ('warrior', 8.2, 'actie', 'Engels', '140 minuten', '6-10-2011', 'Een gepensioneerde staalarbeider en voormalig bokser (Nick Nolte) heeft een groot alcohol probleem. Dit heeft er onder meer voor gezorgd dat zijn gezin uiteen is gevallen. Op zekere dag komt hij tot inkeer en versobert op berouwvolle wijze zijn levenswandel. Zijn jongste zoon (Tom Hardy) accepteert vervolgens maar al te graag zijn aanbod om hem te trainen als worstelaar. Zijn broer (Joel Edgerton) heeft het echter niet zo op zijn vader en werkt aan een eigen loopbaan als worstelaar. Beide broers bereiden zich nu voor op hetzelfde toernooi.', 'https://www.youtube.com/embed/I5kzcwcQA1Q', 'warrior.jpg', 'netflix'),
    ('Mad Max: Fury Road', 8.1, 'actie', 'Engels', '120 minuten', '14-5-2015', 'Achtervolgd door zijn turbulente verleden, is Mad Max (Tom Hardy) ervan overtuigd dat hij alleen kan overleven als hij in zijn eentje opereert. Toch komt hij in contact met een groep die in een oorlogsvoertuig, bestuurd door de imperator Furiosa, door het Wasteland trekt. De groep is op de vlucht voor de tiran Immortan Joe, van wie iets onvervangbaars is gestolen. De woedende krijgsheer stuurt al zijn bendes achter de rebellen aan, wat uitmondt in een meedogenloze, bloedstollende Road War.', 'https://www.youtube.com/embed/hEJnMQG9ev8', 'mad_max.jpg', 'netflix'),
    ('Gladiator', 8.5, 'actie', 'Engels', '156 minuten', '18-5-2000', 'In 180, de gloriedagen van het Romeinse Imperium, overlijdt de grote keizer Antonius Marcus Aurelius (Richard Harris). Hij wordt opgevolgd door zijn wrede zoon Commodus (Joaquin Phoenix). Deze laat de beste strijders vechten om het volk te vermaken. Eén van deze gladiatoren, de door Commodus tot slaaf gedegradeerde generaal Maximus (Russell Crowe), weet zich te verheffen tot de held van het volk. Zijn doel is de beste gladiator aller tijden te worden om zich zo te wreken op keizer Commodus.', 'https://www.youtube.com/embed/owK1qxDselE', 'gladiator.jpg', 'netflix'),
    ('Jaws', 8.1, 'horror', 'Engels', '124 minuten', '20-6-1975', 'De zomervakantie is begonnen en de badgasten van Amity Island, een klein eiland voor de kust van New England, zijn in opperste staat van paraatheid. De zee is echter niet zo vriendelijk als de zon. Een grote witte haai heeft het eiland ontdekt en begint een bloedige jacht op de badgasten. De politie en de badgasten proberen de haai te vangen, maar de haai is veel te slim voor hen. De enige die de haai kan stoppen is de jonge politieagent Brody (Roy Scheider).', 'https://www.youtube.com/embed/U1fu_sA7XhE', 'jaws.jpg','netflix'),
    ('The Shining', 8.4, 'horror', 'Engels', '146 minuten', '13-6-1980', 'Jack Torrance (Jack Nicholson) is een schrijver die in de winter met zijn vrouw Wendy (Shelley Duvall) en zoon Danny (Danny Lloyd) naar het afgelegen Overlook Hotel gaat om er als winterseizoenarbeider te werken. Het hotel is gesloten voor het publiek en wordt alleen gebruikt als een rustplaats voor de winterseizoenarbeiders. Jack is een schrijver die zijn inspiratie nodig heeft en hoopt dat hij die in het hotel zal vinden. Wendy en Danny zijn echter niet zo blij met hun nieuwe woonplaats. Danny heeft namelijk de gave om de toekomst te zien en ziet in het hotel een gevaarlijke plek.', 'https://www.youtube.com/embed/5Cb3ik6zP2I','shining.jpg', 'netflix'),
    ('Split', 7.3, 'horror', 'Engels', '116 minuten', '19-1-2017', 'Kevin (James McAvoy), die lijdt aan een meervoudige persoonlijkheidsstoornis, wordt door een van de persoonlijkheden die in hem leeft, aangezet tot het ontvoeren van drie tienermeisjes waaronder de scherpzinnige Casey (Anya Taylor-Joy). Samen met zijn vertrouwde psychiater Dr. Fletcher (Betty Buckley) moet Kevin een overlevingsstrijd voeren met alle persoonlijkheden die in hem schuilen.', 'https://www.youtube.com/embed/84TouqfIsiI','split.jpg','netflix'),
    ('Dead of Night', 7.6, 'horror', 'Engels', '102 minuten', '17-9-2009', 'In deze film van vier regisseurs vertellen gasten tijdens een etentje sinistere verhalen aan een man met déjà vus.', 'https://www.youtube.com/embed/8UCJz617E8s','dead.jpg', 'netflix'),
    ('A Quiet Place', 7.5, 'horror', 'Engels', '90 minuten', '12-4-2018', 'In A Quiet Place moet een gezin sluipend, lippend en gebarend door het leven gaan. Het minste geluid kan hen overleveren aan geheimzinnige wezens die jagen op het gehoor. In het volle besef dat zelfs een voetstap of gefluister dodelijk kunnen zijn, proberen Evelyn (Emily Blunt) en Lee (John Krasinski) een manier te vinden om hun kinderen koste wat kost te beschermen en hun loerende vijanden te overwinnen.', 'https://www.youtube.com/embed/WR7cc5t7tv8','quiet.jpg', 'netflix');

USE `Fresh_tomatoes`;
DROP TABLE IF EXISTS `fverwacht`;
CREATE TABLE `fverwacht` (
    id MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    titel VARCHAR(100) NOT NULL,
    genre varchar(100) NOT NULL,
    taal varchar(100) NOT NULL,
    datum varchar(100) NULL,
    beschrijving TEXT NOT NULL,
    youtube_trailer_id VARCHAR(100) NOT NULL,
    foto varchar(100) NOT NULL,
    type ENUM('netflix', 'normaal')
);

INSERT INTO fverwacht (titel, genre, taal, datum, beschrijving, youtube_trailer_id, foto, type) VALUES
    ('Guardians of the Galaxy Vol. 3', 'comedy', 'Engels', '4-5-2023', 'Het word een grotere en emotioneleren film dan de vorige twee delen. Meer dan dit is er niet over bekend.', 'https://www.youtube.com/embed/1NQft0-mKDo', 'guardians_of_the_galaxy.jpg', 'normaal'),
    ('costa!!', 'romantiek', 'Nederlands' , '20-10-2022', 'Anna is teleurgesteld door de vervallen staat de Spaanse club waar haar moeder vroeger werkte en gaat aan de slag om het weer de cooldte club in de stad van te maken.', 'https://www.youtube.com/embed/NfmXCWctCMY', 'costa.jpg' , 'normaal'),
    ('The good nurse', 'triller', 'Engels', '26-10-2022', 'een overbelaste ic-vepleegkundige vertrouwt op het werk en thuis op haar onbaatzuchtige nieuwe collega, tot de onverwachte dood van een patient hem in een kwaad daglicht plaatst.', 'https://www.youtube.com/embed/e0DQevX-GZs', 'the_good_nurse.jpg', 'netflix'),
    ('Avatar: The Way of Water', 'sci-fi', 'Engels', '14-12-2022', 'Avatar: The Way of Water vertelt het verhaal van de familie Sully (Jake, Neytiri en hun kinderen) en de problemen waar ze tegenaan lopen, de moeite die ze doen om elkaar te beschermen, de gevechten die ze moeten aangaan om in leven te blijven en de tragedies die ze te verduren krijgen.', 'https://www.youtube.com/embed/a8Gx8wiNbs8','avatar.jpg', 'normaal'),
    ('Prey for the Devil', 'horror', 'Engels', '28-10-2022', 'De jonge, rusteloze non Ann is ervan overtuigd dat duivelsuitbanning haar roeping is en bestudeert in het geheim de rituelen. Wanneer Ann oog in oog komt met een demonische kracht, blijkt die een mysterieus verband te hebben met haar traumatische verleden.', 'https://www.youtube.com/embed/M8QCfvH3q8k','prey.jpg', 'normaal'),
    ('Violent night', 'actie', 'Engels', '1-12-2022', 'Wanneer een groep huurlingen het landgoed van een rijke familie aanvalt, moet de Kerstman ingrijpen om de dag (en Kerstmis) te redden.', 'https://www.youtube.com/embed/G02yIqkDKK8','violent.jpg', 'normaal');

USE `Fresh_tomatoes`;
DROP TABLE IF EXISTS `serie`;
CREATE TABLE `serie` (
    id MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    titel VARCHAR(100) NOT NULL,
    score VARCHAR(100) NOT NULL,
    genre varchar(100) NOT NULL,
    taal varchar(100) NOT NULL,
    seizoen VARCHAR(100) NOT NULL,
    datum VARCHAR(100) NULL,
    beschrijving TEXT NOT NULL,
    youtube_trailer_id VARCHAR(100) NOT NULL,
    foto varchar(100) NOT NULL,
    type ENUM('netflix', 'normaal')
);

INSERT INTO serie (titel, score, genre, taal, seizoen, datum, beschrijving, youtube_trailer_id, foto, type) VALUES
    ('Wanderlust', 5.6, 'Romantiek', 'Engels', '1', '4-9-2018', 'Een therapeute en haar man besluiten om met anderen te gaan daten omdat het niet lukt om hun ingeslapen seksleven na een jarenlang huwelijk nieuw leven in te blazen.', 'https://www.youtube.com/embed/IAPLDP9ZFNI', 'wanderlust.jpeg' , 'netflix'),
    ('Young Royals', 8.3 , 'Romantiek', 'Zweeds' , '1', '1-7-2021' , 'Prins WiIlhelm schikt zich in het leven op zijn prestigieuze nieuwe kostschool Hillerska. Het lijkt lastiger dan hij dacht om zijn hart te volgen.', 'https://www.youtube.com/embed/rHmw87EpGIM', 'youngroyals.jpeg' , 'netflix'),
    ('Virgin River', 7.4 , 'Romantiek', 'Engels' , '2', '9-12-2019' ,  'Een verpleegster uit LA wil een nieuwe start maken. ze verhuist naar een afgelegen stadje in het noorden van Californie en is verrast door wat en wie ze aantreft.', 'https://www.youtube.com/embed/DMNjH5MlQXc', 'virginriver.jpeg' , 'netflix'),
    ('Bridgerton', 7.3 , 'Romantiek', 'Engels' , '2', '25-12-2020' ,  'Acht hechte broers en zussen van de familie Bridgerton zoeken liefde en geluk binnen de Londense high society. Geïnspireerd op de succesvolle romans van Julia Quinn.', 'https://www.youtube.com/embed/gpv7ayf_tyE', 'bridgerton.jpeg' , 'netflix'),
    ('Gilmore Girls', 8.2 , 'Romantiek', 'Engels' , '7', '5-10-2000' ,  'De onafhankelijke, alleenstaande meoder Lorelai voedt haar begaafde, studerende dochter Rory op, die haar doorlopende op een gevatte manier can repliek dient.', 'https://www.youtube.com/embed/YwY86TlfDI0', 'gilmoregirls.jpeg' , 'netflix'),
    ('Lupin', 7.5 , 'Thriller', 'Frans' , '2', '8-1-2021' ,  'geïnspireerd door de avonturen van Arsene Lupin probeert de galante dief Assane Diop zijn vader te wreken voor het onrecht dat een rijke familie hem heeft aangedaan', 'https://www.youtube.com/embed/ga0iTWXCGa0', 'lupin.jpeg' , 'netflix'),
    ('Devil in Ohio', 5.9 , 'Thriller', 'Engels' , '1', '2-9-2022' ,  'Een psychiater is vastbesloten om een jonge patiënt te beschermen die ontsnapt is aan een mysterieuze sekte. Ze neemt haar in huis, waardoor haar eigen gezin en leven in gevaar lopen ', 'https://www.youtube.com/embed/ScEl_smzT3A', 'devilinohio.jpeg', 'netflix'),
    ('OZRK', 8.5 , 'Thriller', 'Engels' , '4', '21-6-2017' ,  'Een financieel adviseur verhuist met zijn gezin van Chicago naar de Ozarks in Missouri, waar hij binnen vijf jaar 50 miljoen dollar moet witwassen voort een drugbaas.', 'https://www.youtube.com/embed/5hAXVqrljbs', 'ozark.jpeg' , 'netflix'),
    ('Alice in Borderland', 7.6 , 'Thriller', 'Japans' , '1', '10-12-2020' ,  'Een doelloze gamer en zijn twee vrienden zitten in een parallelle versie van Tokio, waar ze moeten strijden in een reeks sadistische games om te overleven.', 'https://www.youtube.com/embed/49_44FFKZ1M', 'aliceinborderland.jpeg', 'netflix'),
    ('Ginny & Georgia', 7.4 , 'Comedy', 'Engels' , '1', '24-2-2021' ,  'De vrijgevochten Georgia en haar kinderen Ginny en Austin verhuizen naar het noorden om een frisse start te maken, maar merken dat de weg niet is geplaveid met rozen', 'https://www.youtube.com/embed/e34_mMhe4WQ', 'ginnygeorgia.jpeg' , 'netflix'),
    ('Workin Moms', 7.8 , 'Comedy', 'Engels' , '6', '10-1-2017' ,  'Het zwangerschapsverlof is voorbij. Deze vier moeders moeten weer aan de slag en tegelijkertijd het hoofd bieden aan hun kinderen, bazen, liefde en het leven in Toronto.', 'https://www.youtube.com/embed/gk1vKFcUxyU', 'workinmom.jpeg' , 'netflix'),
    ('BoJack Horseman', 8.8 , 'Comedy', 'Engels' , '6', '22-8-2014' ,  'Ontmoet het meest geliefde sitcom-paard uit de jaren 90, twintig jaar later. een gierigaard met een hart van… niet van goud… iets goudachtigs.Koper misschien?', 'https://www.youtube.com/embed/i1eJMig5Ik4', 'bojackhorseman.jpeg' , 'netflix'),
    ('The Good Place', 8.2 , 'Comedy', 'Engels' , '4', '19-9-2016' ,  'Door een vergissing belandt de egoïstische Eleanor Shellstrop na haar dood op de Goede plaats. Ze wil er absoluut blijven en besluit daarom een beter ment te worden.', 'https://www.youtube.com/embed/9QxRbzFk3zk', 'thegoodplace.jpeg' , 'netflix'),
    ('Cobra Kai', 8.5 , 'Comedy', 'Engels' , '5', '2-5-2018' ,  'Tientallen jaren na het toernooi dat hun leven veranderde, ontbrandt de rivaliteit tussen Johnny en Daniel opnieuw in deze sequel op de Karate kid-films.', 'https://www.youtube.com/embed/xCwwxNbtK6Y', 'cobrakai.jpeg' , 'netflix'),
    ('Desperate Housewives', 7.6 , 'Romantiek', 'Engels' , '8', '3-10-2004' ,  'Geheimen en waarheden ontvouwen zich door het leven van vriendinnen in een buitenwijk, na de mysterieuze zelfmoord van een buurman.', 'https://www.youtube.com/embed/8aY_inuZ_iQ', 'desperatehousewives.jpeg' , 'normaal'),
    ('Gossip Girl', 7.5 , 'Romantiek', 'Engels' , '5', '19-9-2007' ,  'Bevoorrechte tieners die in de Upper East Side van New York wonen, kunnen geen geheim verbergen voor de meedogenloze blogger die altijd kijkt.', 'https://www.youtube.com/embed/eCg1RN-dyQk', 'gossipgirl.jpeg' , 'normaal'),
    ('The summer i turned pretty', 7.4 , 'Romantiek', 'Engels' , '1', '17-6-2022' ,  'Een love triangle tussen een meisje en twee broers. Een verhaal over eerste liefde, eerste liefdesverdriet en de magie van die ene perfecte zomer.', 'https://www.youtube.com/embed/FfAueqEab30', 'thesummeriturnedpretty.jpeg' , 'normaal'),
    ('Pretty Little Liars', 7.4 , 'Romantiek', 'Engels' , '7', '8-6-2010' ,  'Vier vrienden slaan de handen ineen tegen een anonieme vijand die dreigt hun donkerste geheimen te onthullen, terwijl ze ook de verdwijning van hun beste vriend onderzoeken.', 'https://www.youtube.com/embed/ej956ogJxBo', 'prettylittleliars.jpeg' , 'normaal'),
    ('Sex and the city', 7.3 , 'Romantiek', 'Engels' , '6', '6-6-1998' ,  'Vier vrouwelijke New Yorkers roddelen over hun seksleven (of het gebrek daaraan) en vinden eind jaren negentig nieuwe manieren om met het vrouw-zijn om te gaan.', 'https://www.youtube.com/embed/t-rQk0TULOk', 'sexandthecity.jpeg' , 'normaal'),
    ('The vampire diaries', 7.7 , 'Romantiek', 'Engels' , '8', '10-9-2009' ,  'De levens, liefdes, gevaren en rampen in de stad, Mystic Falls, Virginia. Wezens van onuitsprekelijke horror liggen op de loer onder deze stad als een tienermeisje plotseling wordt verscheurd tussen twee vampierbroers.', 'https://www.youtube.com/embed/BmVmhjjkN4E', 'thevampirediaries.jpeg' , 'normaal'),
    ('Modern Family', 8.5 , 'Comedy', 'Engels' , '11', '23-9-2009' ,  'Drie verschillende, maar verwante families worden op hun eigen unieke komische manier geconfronteerd met beproevingen en beproevingen.', 'https://www.youtube.com/embed/HF1Z3ZYipIE', 'modernfamily.jpeg' , 'normaal'),
    ('The Big Bang Theory', 8.2 , 'Comedy', 'Engels' , '12', '24-9-2007' ,  'Een vrouw die van twee briljante maar sociaal onhandige fysici een appartement aan de andere kant van de hal betrekt, laat hen zien hoe weinig ze weten over het leven buiten het laboratorium.', 'https://www.youtube.com/embed/WBb3fojgW0Q', 'thebigbangtheory.jpg' , 'normaal'),
    ('Shameless', 8.6 , 'Comedy', 'Engels' , '10', '9-1-2011' ,  'Een sjofele, pittige, fel loyale familie uit Chicago verontschuldigt zich niet.', 'https://www.youtube.com/embed/uzznfBbbMVc', 'shameless.jpeg' , 'normaal'),
    ('Friends', 8.9 , 'Comedy', 'Engels' , '10', '22-9-1994' ,  'Volgt het persoonlijke en professionele leven van zes twintig- tot dertigjarige vrienden die in Manhattan wonen.', 'https://www.youtube.com/embed/nnn02NDIEiE', 'friends.jpeg' , 'normaal'),
    ('The Office', 9.0 , 'Comedy', 'Engels' , '8', '24-3-2005' ,  'Een mockumentary over een groep typische kantoormedewerkers, waar de werkdag bestaat uit ego-botsingen, ongepast gedrag en verveling.', 'https://www.youtube.com/embed/2iKZmRR9AR4', 'theoffice.jpeg' , 'normaal'),
    ('CSI', 7.7 , 'Thriller', 'Engels' , '14', '6-10-2000' ,  'Serie over een eliteteam van forensisch bewijsonderzoeksexperts van de politie terwijl ze hun zaken in Las Vegas afhandelen.', 'https://www.youtube.com/embed/Y8IYh8pzXGo', 'csi.jpeg' , 'normaal'),
    ('Sherlock', 9.1 , 'Thriller', 'Engels' , '6', '25-7-2010' ,  'Een moderne update vindt dat de beroemde speurder en zijn dokterspartner misdaad oplossen in het 21e-eeuwse Londen.', 'https://www.youtube.com/embed/bWTiCrjGGmc', 'sherlock.jpeg' , 'normaal'),
    ('The X Files', 8.6 , 'Thriller', 'Engels' , '16', '10-9-1993' ,  'Twee FBI Agenten, Fox Mulder de gelovige en Dana Scully de scepticus, onderzoeken het vreemde en onverklaarbare, terwijl verborgen krachten hun inspanningen belemmeren.', 'https://www.youtube.com/embed/KKziOmsJxzE', 'thexfiles.jpeg' , 'normaal'),
    ('Criminal Minds', 8.1 , 'Thriller', 'Engels' , '15', '22-9-2005' ,  'De zaken van de F.B.I. Behavioural Analysis Unit (B.A.U.), een elitegroep van profilers die de gevaarlijkste seriemoordenaars en individuele gruwelijke misdaden van het land analyseren in een poging te anticiperen op hun volgende stappen voordat ze opnieuw toeslaan.', 'https://www.youtube.com/embed/=NTYxiJBbEZk', 'criminalminds.jpeg' , 'normaal'),
    ('Supernatural', 8.4 , 'Thriller', 'Engels' , '15', '14-9-2004' ,  'Twee broers treden in de voetsporen van hun vader als jagers en vechten tegen allerlei soorten kwaadaardige bovennatuurlijke wezens, waaronder monsters, demonen en goden die over de aarde zwerven.', 'https://www.youtube.com/embed/t-775JyzDTk', 'supernatural.jpeg' , 'normaal'),
    ('Stranger things', 8.7,'Horror','Engels', '5', '15-07-2016', 'Hawkins Indiana, jaren 80. Een jongen verdwijnt onder zeer verdachte omstandigheden. Zijn moeder opent samen met de lokale autoriteiten een onderzoek naar de verdwijning . Al snel krijgen ze te maken met een reeks top-secret overheidsexperimenten, angstaanjagende bovennatuurlijke krachten en een zeer vreemd meisje.','https://www.youtube.com/embed/oZ_3eEOrXt8','stranger.jpg','normaal'),
    ('Resident evil', 6.6,'Horror', 'Engels', '1', '14-07-2022', 'Resident Evil vertelt een verhaal over twee tijdlijnen: in de eerste tijdlijn worden de veertienjarige zusjes Jade en Billie Wesker verplaatst naar New Raccoon Stad. Een gefabriceerde, zakelijke stad, die hen wordt opgedrongen terwijl de adolescentie in volle gang is. Maar hoe meer tijd ze daar doorbrengen, hoe meer ze beseffen dat de stad meer is dan het lijkt en dat hun vader duistere geheimen verbergt. Geheimen die de wereld kunnen vernietigen.', 'https://www.youtube.com/embed/uIdjcDTc9Vk&t=2s','resident.jpg', 'normaal'),
    ('Shadow hunters', 6.5, 'Horror', 'Engels', '3', '12-01-2016', 'Shadowhunters zijn half-engel en half-mens en Clary Fray komt er achter dat zij tot dit ras behoort. Haar leven staat op zijn kop. Shadowhunters jagen op demonen, om de mensheid te beschermen. Als de moeder van Clary door een oude vijand wordt ontvoerd begint het leven als Shadowhunter pas echt voor Clary Fray. Gelukkig wordt ze begeleid door Jace Wayland.', 'https://www.youtube.com/embed/aWIM7igneuk','shadow.jpg', 'normaal'),
    ('School tales the series', 5.2, 'Horror', 'Thai', '1', '10-08-2022', 'In deze serie met griezelverhalen, geregisseerd door bekende Thaise horrorregisseurs, dwalen onvoorstelbare gruwelen door de gangen van een middelbare school.', 'https://www.youtube.com/embed/t-CtcO9ktpw','school.jpg', 'normaal'),
    ('The order', 6.7, 'Horror', 'Engels', '2', '07/03/2019', 'The Order volgt de eerstejaars Jack Morton, die zich aansluit bij een geheim fabelachtig gezelschap, genaamd The Order. Hier krijgt hij te maken met een wereld van magie, monsters en intriges. Wanneer Jack steeds dieper in deze wereld duikt, ontdekt hij duistere familiegeheimen en een ondergrondse strijd tussen de weerwolven en de duistere toverkracht. Jack ondergaat een magische en gevaarlijke reis om de waarheid boven tafel te halen, inclusief die van zichzelf.', 'https://www.youtube.com/embed/iD-cFgDDuqM', 'order.jpg','normaal'),
    ('The girl in the mirror',6.2 , 'Horror', 'Spaans' , '1',  '19-08-2022', 'Na een gruwelijk busongeluk op een Spaanse bergkam, waar de buschauffeur door nevel geen zicht heeft op de weg, overlijden de meeste klasgenoten van tiener Alma (Mireia Oriol). Terwijl de scholieren luttele minuten eerder nog keuvelen over hun toekomstplannen, komt er prompt een einde aan hun levens. Alma komt terecht op de intensive care, waar blijkt dat ze aan geheugenverlies lijdt. Ze herkent zichzelf niet op zich is dat logisch: haar gezicht is zwaar gehavend en op haar oog zit een pleister en herinnert zich niets van het incident', 'https://www.youtube.com/embed/4Ef0tjANAiE' ,'thegirl.jpg', 'Netflix'),
    ('Chilling adventures of Sabrina', 7.4, 'Horror', 'Engels', '4', '26-10-2018', 'In de Netflix serie Chilling adventures of Sabrina leven we mee met de avonturen van Sabrina. Ze is half heks, half mens waardoor ze voor de lastige keuze staat om wel of niet gedoopt te worden tijdens de duistere doping op haar 16e verjaardag. Uiteindelijk heeft ze een compromis gesloten dat ze met haar sterfelijke vrienden om mag blijven gaan en gaat ze naar de school van de zwarte Kunsten','https://www.youtube.com/embed/R2gbPxeNk2E', 'sabrina.jpg','Netflix'),
    ('The haunting of hill house', 8.6,'Horror', 'Engels', '1', '12-10-2018', 'In de zomer van 1992 betrekken Hugh en Olivia Crain samen met hun kinderen - Steven, Shirley, Theodora, Luke en Nell - hun nieuwe huis; Hill House. Het plan is om het oude landhuis te renoveren en te verkopen. Door onverwachte omstandigheden en verborgen gebreken moeten ze langer blijven in het huis. Vreemde geluiden en paranormale verschijningen beginnen het gezin op te breken, resulterend in een traumatische gebeurtenis voor het hele gezin. Zesentwintig jaar later komt de familie Crain samen en wordt geconfronteerd met de tijd in Hill House.', 'https://www.youtube.com/embed/3eqxXqJDmcY', 'haunting.jpg','Netflix'),
    ('Sweet home',7.3,'Horror','Koreaans', '1', '18-12-2020', 'Cha Hyun-su, een teruggetrokken middelbare scholier die na een persoonlijke tragedie verhuist naar een nieuw appartementencomplex genaamd Green Home, wordt geconfronteerd met een reeks levens veranderende situaties die hem naar een onbekende wereld brengen, een wereld waar veel dood en verderf is. Mensen veranderen in woeste monsters en zaaien overal terreur. Cha Hyun-su en zijn nieuwe buren moeten vechten voor hun leven, en om hun menselijkheid te behouden.', 'https://www.youtube.com/embed/7rI56NmD33Y','sweeethome.jpg','Netflix'),
    ('Black summer', 6.5,'Horror','Engels', '2', '11-04-2019', 'Wanneer een moeder, Rose, gescheiden is van haar dochter, begint ze aan een schokkende reis en stopt ze bij niets om haar te vinden. Samen met een kleine groep Amerikaanse vluchtelingen moet ze een vijandige nieuwe wereld trotseren en wrede beslissingen nemen tijdens de meest dodelijke zomer van een zombie-apocalyps.', 'https://www.youtube.com/embed/tQA1omPJN24', 'black.jpg','Netflix'),
    ('Snabba cash', 7.6, 'Actie', 'Zweeds', '2', '07-04-2021', 'Stockholm, tien jaar na de gebeurtenissen uit de filmtrilogie. Het is een bruisende tijd waar het verlangen naar status en geld sterker is dan ooit. Techondernemer Leya is vastbesloten om het te redden, wat er ook gebeurteen Ze start een bedrijf met crimineel geld maar komt er op de harde manier achter dat er geen snelle weg naar de top is zonder de prijs te betalen. Zowel de ondernemende jetset als de criminele wereld is brutaler, chaotischer en meedogenlozer dan ooit.', 'https://www.youtube.com/embed/yHFBsGdIBzs', 'snabba.jpg', 'Netflix'),
    ('Cobra kai', 8.5, 'Actie', 'Engels', '5', '02-05-2018', 'Cobra Kai speelt zich af 30 jaar na de gebeurtenissen van het All Valley Karatetournooi in 1984. Johnny Lawrence staat op het punt om zijn beruchte Cobra Kai karate dojo te heropenen. Dit zorgt er voor dat zijn oude rivaliteit met Daniel LaRusso weer opspeelt, die zijn leven probeert te leiden zonder zijn mentor Mr. Miyagi.', 'https://www.youtube.com/embed/sUR9PYwlNaA','cobra.jpg','Netflix'),
    ('Narco saints', 7.4, 'Actie', 'Koreaans', '1', '09-09-2022', 'Een Koreaanse drugbaas wordt in Suriname door zowel de overheid als de politie opgejaagd. Kang In-su, een bescheiden ondernemer, werkt mee aan een geheime missie van de overheid om de drugsbaas op te pakken. Uiteindelijk lijkt In-Su het slachtoffer te gaan worden van de hele operatie; hij wordt er namelijk ingeluisd door de Koreaanse drugsbaron.', 'https://www.youtube.com/embed/ndXDz3vLm_A', 'saints.jpg', 'Netflix'),
    ('Narcos', 8.8, 'Actie', 'Engels', '3', '28-08-2015', 'Narcos vertelt het waargebeurde verhaal van de groei en verspreiding van cocaïnekartels over de hele wereld en de daarmee gepaarde inspanningen van de rechtshandhaving om het hoofd te bieden aan het brute en bloedige conflict. Het draait om de beruchte Colombiaanse kingpin Pablo Escobar en Steven Murphy, een Amerikaanse DEA-agent die naar Colombia is gestuurd om hem te vangen en uiteindelijk te doden.', 'https://www.youtube.com/embed/xl8zdCY-abw', 'narcos.jpg', 'Netflix'),
    ('My name', 7.8, 'Actie', 'Koreaans', '1', '15-10-2021', 'My Name, in het Koreaans uitgebracht onder de naam Mai Neim vertelt het verhaal over een vrouw genaamd Yoon Ji-woos wier vader plotseling komt te overlijden. Volhardend als ze is, maakt ze het haar persoonlijke missie de persoon op te sporen die verantwoordelijk is voor zijn dood en hem een koekje van eigen deeg te geven. Ze werkt voor de drugsbende Dongcheonpa, die onder leiding staat van Choi Moo-jin en sluit zich met de hulp van Choi Moo-jin aan bij de politie. Ze wordt aangesteld bij de narcoticabrigade en wordt een mol voor de drugsbende, om op deze manier uit te zoeken wie de moord op haar vader op zijn geweten heeft.', 'https://www.youtube.com/embed/ZOl7iOrD31Q' ,'myname.jpg', 'Netflix'),
    ('The walking dead', 8.1, 'Actie', 'Engels', '11', '31-10-2010', 'Als politieagent Rick Grimes (Andrew Lincoln) wakker wordt in het ziekenhuis nadat hij is neergeschoten tijdens een achtervolging, lijkt alles verlaten. De bloemen naast zijn bed zijn verlept. Als hij naar buiten gaat om uit te zoeken wat er aan de hand is, vind hij een enorme hoeveelheid lijken naast het ziekenhuis. Als hij verdwaasd verder door het verlaten dorp loopt, komt hij Morgan Jones (Lennie James) en zijn zoon tegen. Eerst wordt Rick door hen als vijand aangezien maar de twee besluiten hem toch op te vangen. Nadat Rick weer bijgekomen is, vertellen Morgan en zijn zoon wat er aan de hand is.', 'https://www.youtube.com/embed/sfAc2U20uyg', 'walking.jpg', 'normaal'),
    ('The 100', 7.6, 'Actie', 'Engels', '7', '19-04-2016', 'Deze show vindt plaats 100 jaar in de toekomst, wanneer de aarde is verlaten wegens radioactiviteit. De laatste overlevende mensen leven in de Ark in een baan om de planeet, maar de Ark heeft niet het eeuwige leven. Dus pakt het repressieve regime 100 overbodige jeugddelinquenten op, en stuurt ze naar de Aarde om te zien of de planeet nog bewoonbaar is.', 'https://www.youtube.com/embed/ia1Fbg96vL0', 'the100.jpg', 'normaal'),
    ('Vikings', 8.5, 'Actie', 'Engels', '6', '03-03-2013', 'Vikings speelt zich af aan het begin van het tijdperk van de Vikingen, het einde van de achtste eeuw, en brengt ons naar de brute en mysterieuze wereld van Ragnar Lothbrok, een Viking krijger en boer die niets liever doet dan ontdekken en plunderen op zee. Zijn ambities zetten hem op gespannen voet met zijn leider Earl Haraldson, die wil dat ze naar het arme Oosten gaan in plaats van naar het onbekende Westen. Wanneer Ragnar een verbond sluit met zijn vriend Floki om een nieuwe boot te bouwen en daarmee vervolgens toch naar het Westen te varen, barst het conflict pas echt los.', 'https://www.youtube.com/embed/9GgxinPwAGc', 'vikings.jpg', 'normaal'),
    ('The flash', 7.6, 'Actie', 'Engels', '9', '07-10-2014', 'Wanneer een ramp met een deeltjesversneller een vernietigende storm veroorzaakt wordt forensisch onderzoeker Barry Allen geraakt door bliksem en belandt in een coma. Maanden later ontwaakt hij met een nieuw verkregen kracht, supersnelheid. Dankzij deze kracht verandert hij in de supersnelle beschermengel van Central City. Barry is geschokt wanneer hij erachter komt dat hij niet de enige "meta-mens" is, die is ontstaan door de ramp met de deeltjesversneller. Wat het nog erger maakt is dat niet iedereen zijn verkregen kracht gebruikt voor het goede. Barry slaat de handen ineen met de overgebleven medewerkers van S.T.A.R. Labs om de onschuldigen te beschermen, al kost hem dit zijn leven.', 'https://www.youtube.com/embed/drQWopZDEEY', 'flash.jpg', 'normaal'),
    ('Arrow', 7.5, 'Actie', 'Engels', '8', '10-10-2012', 'Na een schipbreuk strandt miljardair Oliver Queen op een onbewoond eiland in de Pacific, waar hij slechts één doel heeft: overleven en op een dag terugkeren. Hij wordt vermist en dood gewaand voor vijf jaar, totdat hij levend teruggevonden wordt. Hij is echter niet meer de rijke playboy die hij was. Het eiland heeft hem veranderd en hij draagt een groot geheim met zich mee. Terug in Starling City speelt hij overdag zijn oude rol, maar s nachts is hij een gevaarlijke vechtmachine, die strijdt tegen corruptie en criminaliteit binnen de samenleving; de moderne Robin Hood. Hij heeft tot doel om de fouten van zijn familie recht te zetten en de stad weer te laten leven, zoals hij heeft beloofd aan zijn vader voordat hij stierf.', 'https://www.youtube.com/embed/2yrviapP5uY', 'arrow.jpg', 'normaal'),
    ('Black mirror', 8.8, 'Sci-fi', 'Engels', '5', '04-12-2011', 'In de afgelopen tien jaar heeft de technologie bijna elk aspect van ons leven veranderd, nog voordat we de tijd hadden om het tegen te houden en erover na te denken. In elk huis; op elk bureau; in elke handpalm - een plasma scherm; een monitor; een smartphone - een zwarte spiegel van ons bestaan in de 21e eeuw. Black Mirror is een hedendaags Britse bewerking van de Twilight Zone met verhalen die profiteren van het collectieve onbehagen over onze moderne wereld', 'https://www.youtube.com/embed/jROLrhQkK78','mirror.jpg','Netflix'),
    ('Fate the winx saga', 6.9, 'Sci-fi', 'Engels', '2', '22-01-2021', 'Fate: The Winx Saga is een coming-of-age verhaal over vijf feeën die op het magische internaat Alfea in de Otherworld leren hoe ze hun krachten kunnen beheersen. Ondertussen ontdekken ze ook nog eens hoe ze moeten omgaan met liefde, rivaliteit en de monsters die een bedreiging voor hun bestaan vormen.', 'https://www.youtube.com/embed/dfXRud1AIiw', 'fate.jpg', 'Netflix'),
    ('Manifest', 7.1, 'Sci-fi','Engels', '3', '24-09-2018', 'Montego Air vlucht 828 is veilig geland na een nogal turbulent verlopen routinevlucht. Zowel de passagiers als de bemanningsleden zijn opgelucht wanneer ze de grond weer raken. Tijdens de paar uur die zij in de lucht hebben doorgebracht, is de rest van de wereld vijf jaar verder gekomen. Vrienden, geliefden en familieleden die de hoop hadden opgegeven en verder gingen met hun leven, worden nu geconfronteerd met het feit dat iedereen van vlucht 828 het vermeende ongeval overleefd heeft.', 'https://www.youtube.com/embed/cqIH8ZeYses', 'manifest.jpg', 'Netflix'),
    ('Lucifer', 8.1, 'Sci-fi', 'Engels', '6', '25-01-2016', 'Lucifer is de charmante, charismatische en knappe gevallen engel uit de hel. De ontevreden heerser van de hel doet afstand van zijn titel en verlaat zijn koninkrijk voor de drukte van Los Angeles. Daar vindt hij al gauw de spanning die hij zocht door de politie van Los Angeles bij te staan in het straffen van criminelen. Maar hoe langer hij weg is uit de onderwereld, hoe groter de dreiging wordt dat het ergste uit de geschiedenis van de mensheid kan ontsnappen.', 'https://www.youtube.com/embed/X4bF_quwNtw', 'lucifer.jpg', 'Netflix'),
    ('Ragnarok', 7.5, 'Sci-fi', 'Engels','2', '31-01-2020', 'In het kleine fictieve stadje Edda worden volwassen mensen gedwongen te reageren op klimaatveranderingen. De ijskappen smelten met een snelheid die niemand had verwacht. De wereld maakt lange periodes van droogte door en de winters zijn te warm. Steeds vaker ervaren mensen extreme koude uitbarstingen. In alle opzichten extreme weersomstandigheden. De wereld verandert en sommigen beweren dat we op weg zijn naar een nieuwe Ragnarok. Tenzij iemand op tijd ingrijpt.', 'https://www.youtube.com/embed/7H9AaiBLHCo', 'ragnarok.jpg', 'Netflix' ),
    ('The witcher', 8.2, 'Sci-fi', 'Engels', '3', '20-12-2019', 'Geralt of Rivia, een eenzame, gemuteerde monsterjager, worstelt om zijn plaats te vinden in een wereld waar mensen vaak goddelozer blijken te zijn dan beesten. Maar wanneer het lot hem naar een krachtige tovenares en een jonge prinses met een gevaarlijk geheim brengt, moeten de drie leren om samen het steeds vluchtiger wordende continent te besturen.', 'https://www.youtube.com/embed/ndl1W4ltcmg', 'witcher.jpg', 'normaal'),
    ('Lost in space', 7.3, 'Sci-fi', 'Engels', '3', '13-04-2018', 'In het jaar 2046 ontdekt de familie Robinson met het ruimteschip Jupiter 2 een scheur in de ruimtetijd en storten neer op een onbekende planeet. Lichtjaren van de beoogde bestemming verwijderd moeten de Robinsons en andere kolonisten, die met hen zijn gestrand, strijden tegen een vreemde nieuwe buitenaardse omgeving, terwijl ze proberen de planeet te verlaten.', 'https://www.youtube.com/embed/fzmM0AB60QQ', 'lostinspace.jpg', 'normaal'),
    ('Snowpiercer', 6.9, 'Sci-fi', 'Engels', '3', '17-05/2020', 'Snowpiercer speelt zich af zeven jaar nadat de wereld een bevroren woestenij is geworden. De laatste overlevenden bewonen een gigantische trein, aangedreven door een uit zichzelf bewegende motor die nooit stopt. De trein is opgedeeld in verschillende klassen wat ervoor zorgt dat er aan boord een revolutie ontstaat.','https://www.youtube.com/embed/lGcJL6TG5cA', 'snowpiercer.jpg', 'normaal' ),
    ('Another life', 5.2, 'Sci-fi', 'Engels', '2', '25-07-2019', 'Another Life richt zich op astronaut Niko Breckinridge die alles in het werk stelt om te zoeken naar buitenaardse intelligentie. Ze leidt een team op missie om het ontstaan van een buitenaards artefact te verkennen dat op mysterieuze wijze op aarde terecht is gekomen. Terwijl Niko en haar jonge bemanning onderzoek doen, krijgen ze te maken met onvoorstelbare gevaren voor wat wel eens hun laatste missie zou kunnen zijn.', 'https://www.youtube.com/embed/qAtBbgtMnZ8', 'anotherlife.jpg', 'normaal'),
    ('Better than us', 7.3,'Sci-fi', 'Engels', '1', '23-11-2018', 'In 2029 zijn robots een gewoon onderdeel van het menselijk leven geworden - ze helpen kinderen opvoeden, werken als persoonlijke chauffeurs, bewakers en geliefden. Voor de meeste mensen zijn "Bots" gewoon zielloze machines die routinematig werk uitvoeren, maar ze kunnen ook emoties oproepen. Een groep rebellen, The Liquidators, verwerpen het leven met de bots - en zijn klaar om menselijk bloed te vergieten in hun oorlog tegen de machines.', 'https://www.youtube.com/embed/9CPWD4GRAsA', 'betterthanus.jpg', 'normaal');

USE `Fresh_tomatoes`;
DROP TABLE IF EXISTS `sverwacht`;
CREATE TABLE `sverwacht` (
    id MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    titel VARCHAR(100) NOT NULL,
    genre varchar(100) NOT NULL,
    taal varchar(100) NOT NULL,
    datum VARCHAR(100) NULL,
    beschrijving TEXT NOT NULL,
    youtube_trailer_id VARCHAR(100) NOT NULL,
    foto varchar(100) NOT NULL,
    type ENUM('netflix', 'normaal')
);

INSERT INTO sverwacht (titel, genre, taal, datum, beschrijving, youtube_trailer_id, foto, type) VALUES
    ('28 days haunted', 'Horror', 'Engels', '21-10-2022', 'Drie teams brengen elk 28 dagen door op de meest spookachtige locaties van Amerika voor een paranormaal experiment dat is gebaseerd op de theorieën van Ed en Lorraine Warren.', 'https://www.youtube.com/embed/7nxuEsx99-k','28days.jpg', 'normaal'),
    ('Blackout', 'Actie', 'Engels', '12-10-2022', 'Hij wordt wakker in een Mexicaans ziekenhuis en kan zich niets meer herinneren, maar blijkt doelwit van een kartel te zijn en moet snel de waarheid zien te achterhalen.', 'https://www.youtube.com/embed/lVVAKwZX7Jg','blackout.jpg', 'normaal'),
    ('Glitch', 'Sci-fi', 'Koreaans', '07-10-2022', 'Een jonge vrouw werkt samen met een ufo-enthousiasteling om de plotselinge verdwijning van haar vriend te onderzoeken en stuit op een uitzinnig complot.', 'https://www.youtube.com/embed/inGM8RB6H00', 'glitch.jpg', 'normaal' ),
    ('Alchemy of Souls', 'Comedy', 'Koreaans' , '2022' , 'Een machtige tovenares in het lichaam van een blinde vrouw ontmoet een man uit een prestigieuze familie, die haar hulp nodig heeft om zijn lot te veranderen.', 'https://www.youtube.com/embed/50kLmhGpt1s', 'alchemyofsouls.jpeg' , 'netflix'),
    ('Bad Guys', 'Thriller', 'Thai', '2022' ,  'Een detective keert terug uit zijn schorsing en stelt een onorthodox speciaal onderzoeksteam samen om een seriemoordenaar te pakken te krijgen.', 'https://www.youtube.com/embed/WjGZDxLR1uI', 'badguys.jpeg' , 'netflix'),
    ('Once Upon A Small Town', 'Romantiek', 'Koreaans', '2022' , 'Een dierenarts verhuist tegen zijn zin vanuit de grote stad naar het platteland. daar ontmoet hij een van de inwoners: een politieagent mete een aardig geheim.', 'https://www.youtube.com/embed/IQLcz6wLNg0', 'onceuponasmalltown.jpeg' , 'netflix');